;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-reader.ss" "lang")((modname TerminalsParserTest) (read-case-sensitive #t) (teachpacks ((lib "universe.rkt" "teachpack" "2htdp") (lib "image.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "universe.rkt" "teachpack" "2htdp") (lib "image.rkt" "teachpack" "2htdp")) #f)))
(define NUMBER1 1)
(define NUMBER2 0)
(define NUMBER3 1.2)
(define NUMBER4 4/5)
(define NUMBER5 -1)
(define STRING1 "")
(define STRING2 "a b")
(define STRING3 "a""b")
(define STRING4 "a\"\nb")
(define SYMBOL1 'a)
(define TRUE1 true)
(define TRUE2 #true)
(define TRUE3 #t)
(define TRUE4 #T)
(define FALSE1 false)
(define FALSE2 #false)
(define FALSE3 #f)
(define FALSE4 #F)
(define CHARACTER1 #\space)
(define CHARACTER2 #\a)